CONFIG_AUDIO=y
CONFIG_AUDIO_DMIC=y
CONFIG_SAMPLE_SPECTRUM_DMIC=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_AUDIO2_CLASS=y
CONFIG_SAMPLE_SPECTRUM_USB_MIC=y
CONFIG_SAMPLE_USBD_PID=0x0018
CONFIG_SAMPLE_USBD_PRODUCT="zDSP Spectrum Microphone"
