CONFIG_DISPLAY=y
CONFIG_DSP=y
CONFIG_CMSIS_DSP=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_FPU=y
CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_MPIPE=y
CONFIG_MPIPE_BASE=y
CONFIG_MPIPE_BASE_APP_SRC=y
CONFIG_MPIPE_BASE_APP_SINK=y
CONFIG_MPIPE_BASE_QUEUE=y
CONFIG_MPIPE_BASE_TEE=y
CONFIG_MPIPE_THREADS_NUM=2
CONFIG_MPIPE_THREAD_STACK_SIZE=4096
CONFIG_MPIPE_BASE_APP_SRC_BUF_SZ=512
CONFIG_MPIPE_BASE_APP_SRC_POOL_NUM=4
