/*
 * Copyright 2019 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_SWI_VENDOR_HAL_H_
#define ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_SWI_VENDOR_HAL_H_

#include "hal/RV32M1/swi.h"

#endif /* ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_SWI_VENDOR_HAL_H_ */
