version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci: github: "
  # Main Python dependencies
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "scripts: requirements: "
  # Documentation dependencies
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "doc: "
