"""
Partial build degradation
##########################

Copyright (c) 2026 The Linux Foundation
SPDX-License-Identifier: Apache-2.0

The ``SKIP_*`` switches (see doc/Makefile) drop expensive autogenerated layers
via the ``skip_*`` tags. This extension keeps such a build warning-free under
``-W`` by degrading whatever those layers would have produced:

- it prints a banner naming the disabled layers and warning that the result is
  a preview;
- directives that render a skipped layer are replaced with a placeholder;
- cross-references into a skipped layer resolve to plain text (c-domain
  references are handled by zephyr.doxybridge).

Only the affected directives, domains and reftypes are touched, so genuine
mistakes in the layers that *are* built still surface. Turning the generators
themselves off is done in conf.py (doxyrunner_skip, kconfig_generate_db, ...).
"""

from docutils import nodes
from sphinx.application import Sphinx
from sphinx.config import Config
from sphinx.util import logging
from sphinx.util.console import bold, yellow

logger = logging.getLogger(__name__)

# skip tag -> human description of the layer it disables
_LAYERS = {
    "skip_doxygen": "Doxygen / C API reference",
    "skip_kconfig": "Kconfig option reference and search",
    "skip_board_catalog": "board catalog and per-board hardware tables",
    "skip_external_content": "external board / sample / snippet pages",
}


def _stub_directive(app: Sphinx, domain: str, name: str, message: str | None) -> None:
    """Replace a directive with a placeholder note (or nothing if no message)."""
    original = app.registry.domains[domain].directives[name]

    def run(self):
        if message is None:
            return []
        return [nodes.note("", nodes.paragraph(text=message))]

    stub = type(f"Skipped_{original.__name__}", (original,), {"run": run})
    app.add_directive_to_domain(domain, name, stub, override=True)


def _print_banner(active: list[str]) -> None:
    lines = [bold("This is a PARTIAL documentation build. Disabled layers:")]
    lines += [f"  - {_LAYERS[tag]}" for tag in active]
    lines.append(
        "Their content is replaced by placeholders and cross-references into them "
        "render as plain text. Use it to preview narrative pages only: it must not "
        "be published and cannot be used to validate cross-references."
    )
    # info level (not warning) so it stays visible without failing the -W build
    logger.info(yellow("\n".join(lines)))


def _configure(app: Sphinx, config: Config) -> None:
    active = [tag for tag in _LAYERS if app.tags.has(tag)]
    if not active:
        return

    _print_banner(active)

    # Cross-references into a skipped layer point at targets that were never
    # built; degrade them to plain text. Only the affected domains/reftypes are
    # degraded, so real mistakes in the built layers still warn.
    domains = set()
    zephyr_reftypes = set()
    if "skip_doxygen" in active:
        domains.add("cpp")
    if "skip_kconfig" in active:
        domains.add("kconfig")
    if {"skip_board_catalog", "skip_external_content"} & set(active):
        zephyr_reftypes |= {"board", "board-catalog"}
    if "skip_external_content" in active:
        zephyr_reftypes |= {"code-sample", "code-sample-category"}
    if zephyr_reftypes:
        domains.add("zephyr")

    def degrade(app, env, node, contnode):
        domain = node.get("refdomain")
        if domain not in domains:
            return None
        if domain == "zephyr" and node.get("reftype") not in zephyr_reftypes:
            return None
        return contnode

    if domains:
        app.connect("missing-reference", degrade)

    # Directives that render a skipped layer: show a placeholder naming the
    # layer, or nothing for the inline per-board tables and sample listings.
    if "skip_kconfig" in active:
        _stub_directive(app, "kconfig", "search",
                        "Kconfig option search was skipped in this build.")
    if "skip_board_catalog" in active:
        _stub_directive(app, "zephyr", "board-catalog",
                        "The board catalog was skipped in this build.")
        _stub_directive(app, "zephyr", "board-supported-hw", None)
        _stub_directive(app, "zephyr", "board-supported-runners", None)
    if "skip_external_content" in active:
        _stub_directive(app, "zephyr", "code-sample-listing", None)


def setup(app: Sphinx) -> dict:
    app.connect("config-inited", _configure)

    return {
        "version": "0.1",
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }
