#!/usr/bin/env python3
# Copyright (c) 2025 Basalte bv
#
# SPDX-License-Identifier: Apache-2.0

"""
A script to plot data in a sunburst chart generated by size_report.
When you call the ram_report or rom_report targets you end up
with a json file in the build directory that can be used as input
for this script.

Example:
   ./scripts/footprint/plot.py build/ram.json

Requires plotly to be installed, for example with pip:
   pip install plotly
"""

import argparse
import json

try:
    import plotly.graph_objects as go
except ImportError:
    print("Missing dependency: You need to install plotly (see scripts/requirements-extra.txt).")
    raise


def parse_args():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        allow_abbrev=False,
    )

    parser.add_argument('input', help='Input json file')
    parser.add_argument('--html', help='Output html file')
    parser.add_argument(
        '--depth',
        help='Maximum render depth, pass -1 to render all levels. Defaults to 4',
        type=int,
        default=4,
    )
    parser.add_argument(
        '--diff',
        help='Reference json file to diff against (from a previous build)',
        default=None,
    )

    return parser.parse_args()


def generate_figure(data, depth=4):
    totalsize = data.get('total_size', 0)
    ids = []
    labels = []
    parents = []
    values = []
    hovertext = []

    def iter_node(node: dict, parent=''):
        identifier = node.get('identifier')
        if identifier is None:
            return

        if identifier in ids:
            # Identifiers aren't unique, add a suffix to make them unique
            idx = 0
            while f'{identifier}_{idx}' in ids:
                idx += 1
            identifier = f'{identifier}_{idx}'

        ids.append(identifier)
        labels.append(node.get('name', ''))
        parents.append(parent)
        values.append(node.get('size', 0))

        details = []
        if totalsize > 0:
            details.append(f'percentage: {node.get("size") / totalsize:.2%}')
        if 'address' in node:
            details.append(f'address: 0x{node.get("address"):08x}')
        if 'section' in node:
            details.append(f'section: {node.get("section")}')

        hovertext.append("<br>".join(details))

        for child in node.get('children', ()):
            iter_node(child, identifier)

    iter_node(data.get('symbols', {}))

    fig = go.Figure(
        go.Sunburst(
            ids=ids,
            labels=labels,
            parents=parents,
            values=values,
            hovertext=hovertext,
            branchvalues='total',
            maxdepth=depth,
        ),
        skip_invalid=True,
    )
    fig.update_layout(margin={'t': 0, 'l': 0, 'r': 0, 'b': 0})
    fig.update_traces(textfont=dict(size=24))

    return fig


def _collect_leaf_sizes(node: dict, prefix=''):
    """Recursively collect leaf node sizes as {identifier: size}."""
    identifier = node.get('identifier')
    if identifier is None:
        return {}

    path = f'{prefix}/{identifier}' if prefix else identifier
    children = node.get('children', ())
    if not children:
        return {path: node.get('size', 0)}

    result = {}
    for child in children:
        result.update(_collect_leaf_sizes(child, path))
    return result


def generate_diff_figure(data_current, data_reference):
    """Generate a horizontal bar chart showing size changes between two builds."""
    ref_total = data_reference.get('total_size', 0)
    cur_total = data_current.get('total_size', 0)

    # Collect leaf sizes from both trees
    ref_leaves = {}
    cur_leaves = {}

    for child in data_reference.get('symbols', {}).get('children', ()):
        ref_leaves.update(_collect_leaf_sizes(child))

    for child in data_current.get('symbols', {}).get('children', ()):
        cur_leaves.update(_collect_leaf_sizes(child))

    # Compute deltas
    all_keys = set(ref_leaves.keys()) | set(cur_leaves.keys())
    deltas = []
    for key in all_keys:
        old_sz = ref_leaves.get(key, 0)
        new_sz = cur_leaves.get(key, 0)
        delta = new_sz - old_sz
        if delta != 0:
            deltas.append((key, delta, old_sz, new_sz))

    # Sort by absolute delta descending
    deltas.sort(key=lambda x: abs(x[1]), reverse=True)

    if not deltas:
        fig = go.Figure()
        fig.update_layout(
            title='No differences found between builds',
            xaxis_title='Size change (bytes)',
        )
        return fig

    # Limit to top entries for readability
    max_entries = 40
    if len(deltas) > max_entries:
        deltas = deltas[:max_entries]

    # Reverse so largest bars are at the top of the chart
    deltas.reverse()

    symbols = [d[0].rsplit('/', 1)[-1] for d in deltas]
    changes = [d[1] for d in deltas]
    colors = ['#d32f2f' if d > 0 else '#388e3c' for d in changes]
    hover = [
        f'{d[0]}<br>old: {d[2]} bytes<br>new: {d[3]} bytes<br>delta: {d[1]:+d} bytes'
        for d in deltas
    ]

    fig = go.Figure(
        go.Bar(
            y=symbols,
            x=changes,
            orientation='h',
            marker_color=colors,
            hovertext=hover,
            hoverinfo='text',
        )
    )
    fig.update_layout(
        title=(f'Memory footprint diff (total: {cur_total - ref_total:+d} bytes,'
               f' ref: {ref_total}, cur: {cur_total})'),
        xaxis_title='Size change (bytes)',
        yaxis_title='Symbol',
        margin={'l': 200, 't': 50, 'r': 20, 'b': 50},
        height=max(400, len(deltas) * 25 + 100),
    )

    return fig


def main():
    args = parse_args()

    with open(args.input) as f:
        data = json.load(f)

    if args.diff:
        with open(args.diff) as f:
            data_ref = json.load(f)
        fig = generate_diff_figure(data, data_ref)
    else:
        fig = generate_figure(data, args.depth)

    if args.html:
        fig.write_html(args.html, auto_open=False)
        return

    print("Opening the default browser to render the generated plot.")
    fig.show(renderer="browser")


if __name__ == "__main__":
    main()
