CONFIG_LOG=y
CONFIG_GPIO=y

CONFIG_NETWORKING=y
CONFIG_NET_CONFIG_AUTO_INIT=n
CONFIG_NET_CONNECTION_MANAGER=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_MGMT_EVENT_INFO=y
CONFIG_NET_IPV4=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_WIFI=y
CONFIG_WIFI_NM=y
CONFIG_WIFI_NM_WPA_SUPPLICANT=y
CONFIG_WIFI_USAGE_MODE_STA_AP=y
CONFIG_WIFI_NM_WPA_SUPPLICANT_P2P=y

CONFIG_BIOMETRICS=y
CONFIG_BIOMETRICS_EMUL=y
