# Copyright (c) 2025 The Linux Foundation
#
# SPDX-License-Identifier: Apache-2.0

"""
Abstract base classes for SBOM elements.

This module defines the foundational abstract classes that all SBOM elements
inherit from. These classes are format-agnostic and provide a common interface
for working with SBOM data regardless of the target serialization format.

The design follows the principle that the data model should have no knowledge
of serialization concerns. Format-specific identifiers (like SPDX IDs) are
generated by adapters during serialization, not stored in the model.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any


class ElementType(Enum):
    """
    Type classification for SBOM elements.

    This enum identifies the kind of element being represented, which is
    useful for type-safe processing and serialization decisions.

    Attributes:
        DOCUMENT: A top-level SBOM document container.
        PACKAGE: A software package or component.
        FILE: An individual file within a package.
        RELATIONSHIP: A relationship between two elements.
    """

    DOCUMENT = auto()
    PACKAGE = auto()
    FILE = auto()
    RELATIONSHIP = auto()


@dataclass
class SBOMElement(ABC):
    """
    Abstract base class for all SBOM elements.

    This is the foundation for all SBOM data structures. Elements are
    format-agnostic containers for SBOM data. Format-specific identifiers
    and representations are generated by serializers and adapters, not
    stored directly in the model.

    The internal_id is a session-unique identifier used for cross-referencing
    elements within the model. It is NOT a format-specific ID (like SPDXRef-*
    or CycloneDX bom-ref). Those are generated during serialization.

    Attributes:
        internal_id: Unique identifier within this SBOM generation session.
            Used for internal cross-referencing. Not exposed in serialized output.
        name: Human-readable name for this element.
        comment: Optional comment or description providing additional context.
        annotations: Key-value metadata that serializers can use for
            format-specific features. Keys should be namespaced by format
            (e.g., "spdx:creator_comment", "cyclonedx:pedigree").

    Example:
        >>> # Elements are typically created through concrete subclasses
        >>> from zspdx.model import SBOMPackage
        >>> pkg = SBOMPackage(
        ...     internal_id="pkg-001",
        ...     name="zephyr-kernel",
        ...     comment="The Zephyr RTOS kernel"
        ... )
        >>> pkg.element_type
        <ElementType.PACKAGE: 2>

    Note:
        Subclasses must implement the element_type property to return
        the appropriate ElementType enum value.
    """

    internal_id: str = ""
    name: str = ""
    comment: str = ""
    annotations: dict[str, Any] = field(default_factory=dict)

    @property
    @abstractmethod
    def element_type(self) -> ElementType:
        """
        Return the type of this element.

        Returns:
            ElementType enum value indicating what kind of element this is.
        """
