/*
 * Copyright (c) 2021 BayLibre, SAS
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Driver for ARM Generic Interrupt Controller V3 Interrupt Translation Service
 * @ingroup misc_interfaces
 *
 * The Generic Interrupt Controller (GIC) Interrupt Translation Service translates an input
 * EventID from a device, identified by its DeviceID, determines a corresponding INTID for
 * this input and the target Redistributor and, through this, the target PE for that INTID.
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_INTERRUPT_CONTROLLER_GICV3_ITS_H_
#define ZEPHYR_INCLUDE_DRIVERS_INTERRUPT_CONTROLLER_GICV3_ITS_H_

/** @cond INTERNAL_HIDDEN */

typedef unsigned int (*its_api_alloc_intid_t)(const struct device *dev);
typedef int (*its_api_setup_deviceid_t)(const struct device *dev, uint32_t device_id,
					unsigned int nites);
typedef int (*its_api_map_intid_t)(const struct device *dev, uint32_t device_id,
				   uint32_t event_id, unsigned int intid);
typedef int (*its_api_send_int_t)(const struct device *dev, uint32_t device_id, uint32_t event_id);
typedef uint32_t (*its_api_get_msi_addr_t)(const struct device *dev);

__subsystem struct its_driver_api {
	its_api_alloc_intid_t alloc_intid;
	its_api_setup_deviceid_t setup_deviceid;
	its_api_map_intid_t map_intid;
	its_api_send_int_t send_int;
	its_api_get_msi_addr_t get_msi_addr;
};

/** @endcond */

/**
 * @brief Allocate an LPI INTID.
 *
 * @param dev ITS device.
 *
 * @return The allocated INTID.
 */
static inline int its_alloc_intid(const struct device *dev)
{
	return DEVICE_API_GET(its, dev)->alloc_intid(dev);
}

/**
 * @brief Set up the Interrupt Translation Table for a DeviceID.
 *
 * @param dev ITS device.
 * @param device_id DeviceID to set up.
 * @param nites Number of EventIDs the device will use.
 *
 * @return 0 if successful, negative errno code on failure.
 */
static inline int its_setup_deviceid(const struct device *dev, uint32_t device_id,
				     unsigned int nites)
{
	return DEVICE_API_GET(its, dev)->setup_deviceid(dev, device_id, nites);
}

/**
 * @brief Map an EventID of a DeviceID to an INTID.
 *
 * @param dev ITS device.
 * @param device_id DeviceID of the device generating the event.
 * @param event_id EventID to map.
 * @param intid INTID to map the event to.
 *
 * @return 0 if successful, negative errno code on failure.
 */
static inline int its_map_intid(const struct device *dev, uint32_t device_id,
				uint32_t event_id, unsigned int intid)
{
	return DEVICE_API_GET(its, dev)->map_intid(dev, device_id, event_id, intid);
}

/**
 * @brief Generate the interrupt mapped to an EventID of a DeviceID.
 *
 * @param dev ITS device.
 * @param device_id DeviceID of the device generating the event.
 * @param event_id EventID to generate the interrupt for.
 *
 * @return 0 if successful, negative errno code on failure.
 */
static inline int its_send_int(const struct device *dev, uint32_t device_id, uint32_t event_id)
{
	return DEVICE_API_GET(its, dev)->send_int(dev, device_id, event_id);
}

/**
 * @brief Get the MSI doorbell address.
 *
 * Message-based interrupts are generated by writing the EventID to
 * this address.
 *
 * @param dev ITS device.
 *
 * @return The MSI doorbell address.
 */
static inline uint32_t its_get_msi_addr(const struct device *dev)
{
	return DEVICE_API_GET(its, dev)->get_msi_addr(dev);
}

#endif /* ZEPHYR_INCLUDE_DRIVERS_INTERRUPT_CONTROLLER_GICV3_ITS_H_ */
