CONFIG_ETM_TRACE=y
CONFIG_ETM_TRACE_SINK_ETB=y

# Pull in the Nordic CoreSight driver, which powers the trace domain and routes
# the ETM trace through the ATB fabric to the on-chip ETB sink.
CONFIG_DEBUG_DRIVER=y

CONFIG_LOG=y
