CONFIG_SAMPLE_AA_HU_TRANSPORT_TCP=y

CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_DRIVERS=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y
CONFIG_ETH_NATIVE_TAP=n

CONFIG_MBEDTLS_HEAP_SIZE=65536

# Hold a full I_PCM key frame from the companion accessory sample
CONFIG_SAMPLE_AA_HU_RX_MSG_SIZE=610000
