#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0

"""
Content validation for SPDX documents generated by 'west spdx'.

Usage: pytest verify_spdx_content.py --build-dir <build_dir>
                                     --spdx-version <spdx_version>
                                     --source-dir <source_dir>

Validates that generated SPDX documents contain expected packages, files, relationships, checksums,
and license information for a minimal Zephyr application.

This suite covers what only a real build can show: what the walker discovers from the CMake
file-API, the source tree and the module metadata. How the resulting graph is rendered as SPDX
is covered by scripts/tests/zspdx, which needs no build -- prefer adding a test there when the
assertion does not depend on a real build artifact.
"""

import hashlib
import os

import pytest
from spdx_tools.spdx.model import ExternalPackageRefCategory
from spdx_tools.spdx.model.checksum import ChecksumAlgorithm
from spdx_tools.spdx.model.package import PackagePurpose
from spdx_tools.spdx.model.relationship import RelationshipType

ZEPHYR_ORGANIZATION = "The Zephyr Project"
SPDX_TOOL_PREFIX = "Zephyr SPDX builder"
CPE_ZEPHYR_PREFIX = "cpe:2.3:o:zephyrproject:zephyr:"
UTILITY_TARGETS = {
    "run",
    "flash",
    "debug",
    "debugserver",
    "menuconfig",
    "guiconfig",
    "ram_report",
    "rom_report",
}

# File name constants (as they appear in SPDX documents)
FILE_MAIN_C = "./src/main.c"
FILE_LIBAPP_A = "./app/libapp.a"
FILE_LIBKERNEL_A = "./zephyr/kernel/libkernel.a"
FILE_LIBZEPHYR_A = "./zephyr/libzephyr.a"
FILE_ZEPHYR_ELF = "./zephyr/zephyr.elf"

PKG_USED_MODULE_SOURCES = "sbom_used_module-sources"
PKG_UNUSED_MODULE_SOURCES = "sbom_unused_module-sources"
PKG_USED_MODULE_DEPS = "sbom_used_module-deps"
PKG_UNUSED_MODULE_DEPS = "sbom_unused_module-deps"

# Application identity: the supplier passed to 'west spdx --supplier' by CMakeLists.txt,
# and the version read from this test application's own VERSION file.
APP_SUPPLIER = "SBOM Test Application Supplier"
APP_VERSION = "1.2.3"

# Values declared in the "sbom:" section of used_module/zephyr/module.yml.
USED_MODULE_SBOM_LICENSE = "Apache-2.0"
USED_MODULE_SBOM_ORGANIZATION = "SBOM Test Upstream Organization"
USED_MODULE_SBOM_VERSION = "1.2.3"
USED_MODULE_SBOM_PURL = "pkg:github/sbom-test-upstream/sbom_used_module"

FILE_USED_MODULE_C = "./src/answer.c"
FILE_UNUSED_MODULE_C = "unused.c"
FILE_REUSE_TOML_C = "./src/no_header.c"

# Common license and copyright strings as they appear in the SBOM.
LICENSE_APACHE = "Apache-2.0"
COPYRIGHT_ZEPHYR = "Copyright The Zephyr Project Contributors"
COPYRIGHT_LINUX_FOUNDATION = "Copyright (C) 2026 The Linux Foundation"

# answer.c declares its copyright with the SPDX tag, and the scanner stores each
# notice canonically between newlines, so this is the exact value in the SBOM.
EXPECTED_USED_MODULE_COPYRIGHT = f"\nSPDX-FileCopyrightText: {COPYRIGHT_ZEPHYR}\n"


def find_file_by_name(doc, name):
    """Find a file in a document by exact name."""

    return next((f for f in doc.files if f.name == name), None)


def file_license_ids(spdx_file):
    """Return the list of license identifiers detected inside a file."""
    return [str(lic) for lic in spdx_file.license_info_in_file]


def find_package_by_name(doc, name):
    """Find a package in a document by exact name."""
    return next((p for p in doc.packages if p.name == name), None)


def get_relationships_for_element(doc, spdx_id, rel_type):
    """Get all relationships of a given type for a specific element."""
    return [
        r
        for r in doc.relationships
        if r.spdx_element_id == spdx_id and r.relationship_type == rel_type
    ]


def find_doc_ref_id(doc, namespace):
    """Find the DocumentRef ID in doc that points to the given namespace."""
    return next(
        (
            ref.document_ref_id
            for ref in doc.creation_info.external_document_refs
            if ref.document_uri == namespace
        ),
        None,
    )


def file_sha1(path):
    """Calculate the SHA1 hash of a file."""
    with open(path, "rb") as f:
        return hashlib.sha1(f.read(), usedforsecurity=False).hexdigest()


def get_purl_refs(package):
    """Collect purl external references from a package."""
    return [
        ref.locator
        for ref in package.external_references
        if ref.category == ExternalPackageRefCategory.PACKAGE_MANAGER
        and ref.reference_type == "purl"
    ]


def get_cpe_refs(package):
    """Collect CPE 2.3 external references from a package."""
    return [
        ref.locator
        for ref in package.external_references
        if ref.category == ExternalPackageRefCategory.SECURITY and ref.reference_type == "cpe23Type"
    ]


def expected_zephyr_cpe(zephyr_version):
    """Build the CPE expected for a Zephyr version, with any pre-release qualifier
    moved to the CPE 'update' field."""
    release, _, update = zephyr_version.partition("-")
    return f"{CPE_ZEPHYR_PREFIX}{release}:{update or '-'}:*:*:*:*:*:*"


def get_supplier_name(package):
    """Return the package supplier as a string, or None if unset."""
    if package.supplier is None:
        return None
    return str(package.supplier)


def has_relationship(doc, spdx_element_id, rel_type, related_id):
    """Return True if doc has a relationship of rel_type to related_id."""
    for rel in doc.relationships:
        if rel.spdx_element_id != spdx_element_id:
            continue
        if rel_type not in str(rel.relationship_type):
            continue
        if str(rel.related_spdx_element_id) == related_id:
            return True
    return False


def first_module_sources_package(zephyr_doc):
    """Return the first module *-sources package, excluding zephyr-sources."""
    return next(
        (
            pkg
            for pkg in zephyr_doc.packages
            if pkg.name.endswith("-sources") and pkg.name != "zephyr-sources"
        ),
        None,
    )


class TestCreators:
    """Tests that creator information reflects the tree the SBOM was generated from."""

    def test_creators_reflect_the_tree(self, modules_doc, zephyr_version):
        """The organization is fixed, but the tool version is read from the tree."""
        creators = [str(c) for c in modules_doc.creation_info.creators]
        assert f"Organization: {ZEPHYR_ORGANIZATION}" in creators, (
            f"modules-deps.spdx: expected Organization creator, got {creators}"
        )
        expected_tool = f"Tool: {SPDX_TOOL_PREFIX}-{zephyr_version}"
        assert expected_tool in creators, (
            f"modules-deps.spdx: expected '{expected_tool}', got {creators}"
        )


class TestAppDocument:
    """Tests for app.spdx document validation."""

    def test_app_sources_package_exists(self, app_doc):
        """Test there is only one package named app-sources."""
        pkg_names = [p.name for p in app_doc.packages]
        has_only_app_sources = len(pkg_names) == 1 and pkg_names[0] == "app-sources"
        assert has_only_app_sources, (
            f"app.spdx: expected only 'app-sources' package, got {pkg_names}"
        )

    def test_app_sources_spdx_id(self, app_doc):
        """Test that app-sources package has correct SPDX ID."""
        app_pkg = find_package_by_name(app_doc, "app-sources")
        assert app_pkg is not None, "app.spdx: app-sources package not found"
        assert app_pkg.spdx_id == "SPDXRef-app-sources", (
            f"app.spdx: app-sources spdx_id is '{app_pkg.spdx_id}'"
        )

    @pytest.mark.min_spdx_version("2.3")
    def test_primary_package_purpose_spdx_23(self, app_doc):
        """Test that primary_package_purpose is SOURCE for SPDX 2.3."""
        app_pkg = find_package_by_name(app_doc, "app-sources")
        assert app_pkg is not None, "app.spdx: app-sources package not found"
        assert app_pkg.primary_package_purpose == PackagePurpose.SOURCE, (
            f"app.spdx: primary_package_purpose is {app_pkg.primary_package_purpose}, "
            "expected PackagePurpose.SOURCE"
        )

    def test_only_file_is_main_c(self, app_doc):
        """Test that the only file in the package is main.c."""
        main_c_spdx = find_file_by_name(app_doc, FILE_MAIN_C)
        assert len(app_doc.files) == 1 and main_c_spdx is not None, (
            f"app.spdx: expected only 'main.c' file, got {len(app_doc.files)} files"
        )

    def test_verification_code(self, app_doc):
        """Test that verification code is present when files are analyzed."""
        app_pkg = find_package_by_name(app_doc, "app-sources")
        assert app_pkg is not None, "app.spdx: app-sources package not found"
        if not app_pkg.files_analyzed:
            pytest.skip("files_analyzed is False")
        assert app_pkg.verification_code is not None, (
            "app.spdx: app-sources has files_analyzed=True but no verification_code"
        )

    def test_contains_relationships(self, app_doc):
        """Test that CONTAINS relationships exist from app-sources package."""
        app_pkg = find_package_by_name(app_doc, "app-sources")
        assert app_pkg is not None, "app.spdx: app-sources package not found"
        contains_rels = [
            r
            for r in app_doc.relationships
            if r.relationship_type == RelationshipType.CONTAINS
            and r.spdx_element_id == app_pkg.spdx_id
        ]
        assert len(contains_rels) == 1, (
            f"app.spdx: expected exactly 1 CONTAINS relationship, got {len(contains_rels)}"
        )

    def test_main_c_hash_correct(self, app_doc, source_dir):
        """Test that main.c has the correct SHA1 and SHA256 hashes."""
        main_c_spdx = find_file_by_name(app_doc, FILE_MAIN_C)
        assert main_c_spdx is not None, f"app.spdx: {FILE_MAIN_C} not found"

        # Read file once for computing both hashes
        main_c_path = os.path.join(source_dir, "src", "main.c")
        assert os.path.exists(main_c_path), f"Source file not found: {main_c_path}"

        with open(main_c_path, "rb") as f:
            file_content = f.read()
            expected_sha1 = hashlib.sha1(file_content, usedforsecurity=False).hexdigest()
            expected_sha256 = hashlib.sha256(file_content, usedforsecurity=False).hexdigest()

        # Validate SHA1 checksum
        sha1_checksums = [c for c in main_c_spdx.checksums if c.algorithm == ChecksumAlgorithm.SHA1]
        assert len(sha1_checksums) > 0, "app.spdx: main.c has no SHA1 checksum"

        actual_sha1 = sha1_checksums[0].value
        assert actual_sha1 == expected_sha1, (
            f"app.spdx: main.c SHA1 mismatch. Expected '{expected_sha1}', got '{actual_sha1}'"
        )

        # Validate SHA256 checksum
        sha256_checksums = [
            c for c in main_c_spdx.checksums if c.algorithm == ChecksumAlgorithm.SHA256
        ]
        assert len(sha256_checksums) > 0, "app.spdx: main.c has no SHA256 checksum"

        actual_sha256 = sha256_checksums[0].value
        assert actual_sha256 == expected_sha256, (
            f"app.spdx: main.c SHA256 mismatch. Expected '{expected_sha256}', got '{actual_sha256}'"
        )

    def test_main_c_license_correct(self, app_doc):
        """Test that main.c has Apache-2.0 license info."""
        main_c_spdx = find_file_by_name(app_doc, FILE_MAIN_C)
        assert main_c_spdx is not None, f"app.spdx: {FILE_MAIN_C} not found"

        assert main_c_spdx.license_info_in_file, "app.spdx: main.c has no license_info_in_file"

        license_strs = [str(lic) for lic in main_c_spdx.license_info_in_file]
        has_apache = any(LICENSE_APACHE in lic for lic in license_strs)
        assert has_apache, (
            f"app.spdx: main.c license should be {LICENSE_APACHE}, got {license_strs}"
        )

    def test_main_c_copyright_correct(self, app_doc):
        """Test that main.c has correct copyright text."""
        main_c_spdx = find_file_by_name(app_doc, FILE_MAIN_C)
        assert main_c_spdx is not None, f"app.spdx: {FILE_MAIN_C} not found"

        assert main_c_spdx.copyright_text, "app.spdx: main.c has no copyright_text"

        copyright_text = str(main_c_spdx.copyright_text)
        expected = [COPYRIGHT_ZEPHYR, COPYRIGHT_LINUX_FOUNDATION]
        for s in expected:
            assert s in copyright_text, f"main.c copyright missing '{s}', got '{copyright_text}'"


class TestZephyrDocument:
    """Tests for zephyr.spdx document validation."""

    def test_has_packages(self, zephyr_doc):
        """Test that zephyr.spdx has at least one package."""
        assert len(zephyr_doc.packages) >= 1, "zephyr.spdx: no packages found"

    def test_zephyr_sources_package_exists(self, zephyr_doc):
        """Test that zephyr-sources package exists."""
        pkg_names = [p.name for p in zephyr_doc.packages]
        assert "zephyr-sources" in pkg_names, (
            f"zephyr.spdx: expected 'zephyr-sources' package, got {pkg_names}"
        )

    def test_zephyr_sources_spdx_id(self, zephyr_doc):
        """Test that zephyr-sources package has correct SPDX ID."""
        zephyr_pkgs = [p for p in zephyr_doc.packages if p.name == "zephyr-sources"]
        if not zephyr_pkgs:
            pytest.skip("zephyr-sources package not found")
        assert zephyr_pkgs[0].spdx_id == "SPDXRef-zephyr-sources", (
            f"zephyr.spdx: zephyr-sources spdx_id is '{zephyr_pkgs[0].spdx_id}'"
        )

    def test_has_many_files(self, zephyr_doc):
        """Test that zephyr.spdx has more than 10 files."""
        assert len(zephyr_doc.files) > 10, (
            f"zephyr.spdx: expected >10 files, got {len(zephyr_doc.files)}"
        )

    def test_has_kernel_files(self, zephyr_doc):
        """Test that zephyr.spdx contains kernel files."""
        file_names = [f.name for f in zephyr_doc.files]
        has_kernel_file = any("kernel" in name.lower() for name in file_names)
        assert has_kernel_file, "zephyr.spdx: no files with 'kernel' in path found"

    def test_files_have_sha1_checksum(self, zephyr_doc):
        """Test that all files have SHA1 checksums."""
        for f in zephyr_doc.files:
            sha1s = [c for c in f.checksums if c.algorithm == ChecksumAlgorithm.SHA1]
            assert len(sha1s) > 0, f"zephyr.spdx: file '{f.name}' has no SHA1 checksum"

    def test_files_have_apache_license(self, zephyr_doc):
        """Test that some files have Apache-2.0 license info."""
        files_with_apache = [
            f
            for f in zephyr_doc.files
            if f.license_info_in_file
            and any(LICENSE_APACHE in str(lic) for lic in f.license_info_in_file)
        ]
        assert len(files_with_apache) > 0, (
            f"zephyr.spdx: no files have {LICENSE_APACHE} license info"
        )

    def test_verification_code(self, zephyr_doc):
        """Test that verification code is present when files are analyzed."""
        zephyr_pkgs = [p for p in zephyr_doc.packages if p.name == "zephyr-sources"]
        if not zephyr_pkgs:
            pytest.skip("zephyr-sources package not found")
        zephyr_pkg = zephyr_pkgs[0]
        if not zephyr_pkg.files_analyzed:
            pytest.skip("files_analyzed is False")
        assert zephyr_pkg.verification_code is not None, (
            "zephyr.spdx: zephyr-sources has files_analyzed=True but no verification_code"
        )


class TestBuildDocument:
    """Tests for build.spdx document validation."""

    def test_has_packages(self, build_doc):
        """Test that build.spdx has at least one package."""
        assert len(build_doc.packages) >= 1, "build.spdx: no packages found"

    def test_packages_have_valid_spdx_ids(self, build_doc):
        """Test that all packages have valid SPDX IDs."""
        for pkg in build_doc.packages:
            assert pkg.spdx_id.startswith("SPDXRef-"), (
                f"build.spdx: package '{pkg.name}' has invalid spdx_id '{pkg.spdx_id}'"
            )

    def test_has_multiple_relationship_types(self, build_doc):
        """Test that build.spdx has more than one relationship type."""
        rel_types = set(r.relationship_type for r in build_doc.relationships)
        assert len(rel_types) > 1, (
            f"build.spdx: only {len(rel_types)} relationship type(s) found, expected more than 1"
        )

    def test_has_external_document_refs(self, build_doc):
        """Test that build.spdx has external document references."""
        ext_refs = build_doc.creation_info.external_document_refs
        assert len(ext_refs) > 0, "build.spdx: no external document references found"

    def test_app_package_excludes_generated_files(self, build_doc):
        """Build-tree generated files must not land in the app package (only libapp.a)."""
        app_pkg = find_package_by_name(build_doc, "app")
        assert app_pkg is not None, "build.spdx: app package not found"
        contained = {
            str(r.related_spdx_element_id)
            for r in get_relationships_for_element(
                build_doc, app_pkg.spdx_id, RelationshipType.CONTAINS
            )
        }
        app_files = [f.name for f in build_doc.files if f.spdx_id in contained]
        assert app_files == [FILE_LIBAPP_A], (
            f"build.spdx: app package should contain only {FILE_LIBAPP_A}, got {app_files}"
        )

    def test_utility_targets_excluded(self, build_doc):
        """Test that CMake UTILITY targets are not emitted as packages."""
        package_names = {pkg.name for pkg in build_doc.packages}
        found = package_names & UTILITY_TARGETS
        assert not found, f"build.spdx: UTILITY targets should be excluded, found {sorted(found)}"


class TestPackageProvenance:
    """Tests for package supplier and purl metadata."""

    def test_zephyr_sources_version(self, zephyr_doc, zephyr_version):
        """Test zephyr-sources reports the version from the Zephyr VERSION file."""
        pkg = find_package_by_name(zephyr_doc, "zephyr-sources")
        assert pkg is not None, "zephyr.spdx: zephyr-sources package not found"
        assert pkg.version == zephyr_version, (
            f"zephyr.spdx: zephyr-sources version is '{pkg.version}', expected '{zephyr_version}'"
        )

    def test_zephyr_sources_cpe(self, zephyr_doc, zephyr_version):
        """Test zephyr-sources carries the CPE for the built Zephyr version."""
        pkg = find_package_by_name(zephyr_doc, "zephyr-sources")
        assert pkg is not None, "zephyr.spdx: zephyr-sources package not found"
        cpes = get_cpe_refs(pkg)
        assert expected_zephyr_cpe(zephyr_version) in cpes, (
            f"zephyr.spdx: zephyr-sources missing CPE "
            f"'{expected_zephyr_cpe(zephyr_version)}', got {cpes}"
        )

    def test_zephyr_deps_version(self, modules_doc, zephyr_version):
        """Test zephyr-deps reports the same version as zephyr-sources."""
        if len(modules_doc.packages) == 0:
            pytest.skip("No packages in modules-deps.spdx")
        pkg = find_package_by_name(modules_doc, "zephyr-deps")
        assert pkg is not None, "modules-deps.spdx: zephyr-deps package not found"
        assert pkg.version == zephyr_version, (
            f"modules-deps.spdx: zephyr-deps version is '{pkg.version}', "
            f"expected '{zephyr_version}'"
        )

    def test_zephyr_deps_cpe(self, modules_doc, zephyr_version):
        """Test zephyr-deps carries the CPE for the built Zephyr version."""
        if len(modules_doc.packages) == 0:
            pytest.skip("No packages in modules-deps.spdx")
        pkg = find_package_by_name(modules_doc, "zephyr-deps")
        assert pkg is not None, "modules-deps.spdx: zephyr-deps package not found"
        cpes = get_cpe_refs(pkg)
        assert expected_zephyr_cpe(zephyr_version) in cpes, (
            f"modules-deps.spdx: zephyr-deps missing CPE "
            f"'{expected_zephyr_cpe(zephyr_version)}', got {cpes}"
        )


class TestNTIAMinimumElements:
    """Assert the NTIA/CISA minimum SBOM elements are present in every document.

    These mirror the checks in the SPDX project's ntia-conformance-checker so a
    regression that would make a generated document non-conformant fails here, in a
    build that already produces the documents, rather than in downstream tooling.
    """

    @pytest.fixture(params=["app_doc", "zephyr_doc", "build_doc", "modules_doc"])
    def doc_with_name(self, request):
        """Parametrized fixture providing each document with its name."""
        doc = request.getfixturevalue(request.param)
        name_map = {
            "app_doc": "app.spdx",
            "zephyr_doc": "zephyr.spdx",
            "build_doc": "build.spdx",
            "modules_doc": "modules-deps.spdx",
        }
        return doc, name_map[request.param]

    def test_author_of_sbom_data(self, doc_with_name):
        """Minimum element: author of the SBOM data."""
        doc, doc_name = doc_with_name
        assert doc.creation_info.creators, f"{doc_name}: no SBOM author (Creator) recorded"

    def test_timestamp(self, doc_with_name):
        """Minimum element: timestamp."""
        doc, doc_name = doc_with_name
        assert doc.creation_info.created, f"{doc_name}: no creation timestamp recorded"

    def test_component_names(self, doc_with_name):
        """Minimum element: component name."""
        doc, doc_name = doc_with_name
        unnamed = [p.spdx_id for p in doc.packages if not p.name]
        assert not unnamed, f"{doc_name}: packages without a name: {unnamed}"

    def test_component_identifiers(self, doc_with_name):
        """Minimum element: other unique identifiers (the SPDX ID at minimum)."""
        doc, doc_name = doc_with_name
        unidentified = [p.name for p in doc.packages if not p.spdx_id]
        assert not unidentified, f"{doc_name}: packages without an SPDX ID: {unidentified}"

    def test_component_versions(self, doc_with_name):
        """Minimum element: version of the component."""
        doc, doc_name = doc_with_name
        unversioned = [p.name for p in doc.packages if not p.version]
        assert not unversioned, f"{doc_name}: packages without a version: {unversioned}"

    def test_component_suppliers(self, doc_with_name):
        """Minimum element: supplier name.

        A supplier of NOASSERTION counts as missing: the element has to name an entity.
        """
        doc, doc_name = doc_with_name
        unsupplied = [
            p.name for p in doc.packages if get_supplier_name(p) in (None, "NOASSERTION", "")
        ]
        assert not unsupplied, f"{doc_name}: packages without a supplier: {unsupplied}"

    def test_dependency_relationships(self, doc_with_name):
        """Minimum element: dependency relationships.

        The document has to describe at least one of the packages it defines, which is
        what an SBOM consumer follows to find the subject of the document.
        """
        doc, doc_name = doc_with_name
        package_ids = {p.spdx_id for p in doc.packages}
        describes = [
            r
            for r in doc.relationships
            if r.relationship_type == RelationshipType.DESCRIBES
            and r.related_spdx_element_id in package_ids
        ]
        assert describes, f"{doc_name}: no DESCRIBES relationship pointing at a package"

    def test_module_sources_depend_on_zephyr_sources(self, zephyr_doc):
        """Every module source package states its relationship to Zephyr itself.

        Without this the module packages sit in the document with no edge to anything,
        which reads as "no dependency information" to an SBOM consumer.
        """
        zephyr_pkg = find_package_by_name(zephyr_doc, "zephyr-sources")
        assert zephyr_pkg is not None, "zephyr.spdx: zephyr-sources package not found"

        module_pkgs = [
            p
            for p in zephyr_doc.packages
            if p.name.endswith("-sources") and p.name != "zephyr-sources"
        ]
        assert module_pkgs, "zephyr.spdx: no module source packages found"

        unlinked = [
            p.name
            for p in module_pkgs
            if not has_relationship(zephyr_doc, p.spdx_id, "DEPENDENCY_OF", zephyr_pkg.spdx_id)
        ]
        assert not unlinked, (
            f"zephyr.spdx: module source packages with no DEPENDENCY_OF edge to "
            f"zephyr-sources: {unlinked}"
        )


class TestApplicationIdentity:
    """Tests for the application's own supplier and version.

    These are the two minimum elements 'west spdx' cannot derive from the west manifest:
    the version comes from the application's VERSION file and the supplier from
    ``--supplier``. The build packages inherit both, since the build produced them.
    """

    def test_app_sources_supplier(self, app_doc):
        """--supplier reaches the application package."""
        pkg = find_package_by_name(app_doc, "app-sources")
        assert pkg is not None, "app.spdx: app-sources package not found"
        assert get_supplier_name(pkg) == f"Organization: {APP_SUPPLIER}", (
            f"app.spdx: app-sources supplier is '{get_supplier_name(pkg)}'"
        )

    def test_app_sources_version(self, app_doc):
        """The application's VERSION file supplies its package version."""
        pkg = find_package_by_name(app_doc, "app-sources")
        assert pkg is not None, "app.spdx: app-sources package not found"
        assert pkg.version == APP_VERSION, (
            f"app.spdx: app-sources version is '{pkg.version}', expected '{APP_VERSION}'"
        )

    def test_build_packages_inherit_app_identity(self, build_doc):
        """Build outputs carry the same supplier and version as the application."""
        assert build_doc.packages, "build.spdx: no packages"
        for pkg in build_doc.packages:
            assert get_supplier_name(pkg) == f"Organization: {APP_SUPPLIER}", (
                f"build.spdx: {pkg.name} supplier is '{get_supplier_name(pkg)}'"
            )
            assert pkg.version == APP_VERSION, (
                f"build.spdx: {pkg.name} version is '{pkg.version}', expected '{APP_VERSION}'"
            )

    def test_final_image_has_package_checksum(self, build_doc):
        """The final image's package carries a checksum of its artifact."""
        pkg = find_package_by_name(build_doc, "zephyr_final")
        assert pkg is not None, "build.spdx: zephyr_final package not found"
        algorithms = {c.algorithm for c in pkg.checksums}
        assert ChecksumAlgorithm.SHA256 in algorithms, (
            f"build.spdx: zephyr_final has no SHA256 PackageChecksum, got {algorithms}"
        )


class TestModuleSbomMetadata:
    """Tests for the ``sbom:`` section a module declares in :file:`zephyr/module.yml`."""

    @pytest.fixture(params=[PKG_USED_MODULE_SOURCES, PKG_USED_MODULE_DEPS])
    def used_module_package(self, request, zephyr_doc, modules_doc):
        """The used module's source and dependency packages, which share the metadata."""
        doc = zephyr_doc if request.param.endswith("-sources") else modules_doc
        pkg = find_package_by_name(doc, request.param)
        assert pkg is not None, f"package '{request.param}' not found"
        return pkg

    def test_declared_license_from_module_yml(self, used_module_package):
        """``sbom: license:`` becomes the package's declared license."""
        declared = str(used_module_package.license_declared)
        assert declared == USED_MODULE_SBOM_LICENSE, (
            f"{used_module_package.name}: license_declared is '{declared}', "
            f"expected '{USED_MODULE_SBOM_LICENSE}'"
        )

    def test_originator_from_module_yml(self, used_module_package):
        """``sbom: upstream: organization:`` becomes the package originator."""
        originator = used_module_package.originator
        originator = str(originator) if originator else None
        assert originator == f"Organization: {USED_MODULE_SBOM_ORGANIZATION}", (
            f"{used_module_package.name}: originator is '{originator}'"
        )

    def test_supplier_is_still_zephyr(self, used_module_package):
        """The supplier stays the Zephyr Project: that is where the code is fetched from."""
        supplier = get_supplier_name(used_module_package)
        assert supplier == f"Organization: {ZEPHYR_ORGANIZATION}", (
            f"{used_module_package.name}: supplier is '{supplier}'"
        )

    def test_upstream_version_from_module_yml(self, used_module_package):
        """``sbom: upstream: version:`` is preferred over the mirror's commit hash."""
        assert used_module_package.version == USED_MODULE_SBOM_VERSION, (
            f"{used_module_package.name}: version is '{used_module_package.version}', "
            f"expected '{USED_MODULE_SBOM_VERSION}'"
        )

    def test_upstream_purl_present(self, used_module_package):
        """``sbom: upstream: url:`` adds a purl pointing at the upstream project."""
        purls = get_purl_refs(used_module_package)
        expected = f"{USED_MODULE_SBOM_PURL}@{USED_MODULE_SBOM_VERSION}"
        assert expected in purls, (
            f"{used_module_package.name}: expected upstream purl '{expected}', got {purls}"
        )


class TestPackageComments:
    """Tests for package role comments."""

    def test_zephyr_sources_comment(self, zephyr_doc):
        """Test zephyr-sources comment describes a source package."""
        pkg = find_package_by_name(zephyr_doc, "zephyr-sources")
        assert pkg is not None, "zephyr.spdx: zephyr-sources package not found"
        assert pkg.comment and "Source package" in str(pkg.comment), (
            f"zephyr.spdx: zephyr-sources comment should mention 'Source package', "
            f"got '{pkg.comment}'"
        )

    def test_module_sources_comment(self, zephyr_doc):
        """Test first module-sources comment describes a source package."""
        pkg = first_module_sources_package(zephyr_doc)
        if pkg is None:
            pytest.skip("No module-sources packages in zephyr.spdx")
        assert pkg.comment and "Source package" in str(pkg.comment), (
            f"zephyr.spdx: {pkg.name} comment should mention 'Source package', got '{pkg.comment}'"
        )

    def test_no_utility_target_comments(self, app_doc, zephyr_doc, build_doc, modules_doc):
        """Test that no package carries the old UTILITY target comment."""
        for doc_name, doc in [
            ("app.spdx", app_doc),
            ("zephyr.spdx", zephyr_doc),
            ("build.spdx", build_doc),
            ("modules-deps.spdx", modules_doc),
        ]:
            for pkg in doc.packages:
                if pkg.comment and str(pkg.comment) == "Utility target; no files":
                    pytest.fail(f"{doc_name}: package '{pkg.name}' has UTILITY target comment")


class TestCrossReferences:
    """Tests for cross-document reference validation."""

    def test_external_ref_to_zephyr(self, build_doc):
        """Test that build.spdx has external reference to zephyr document."""
        ext_refs = build_doc.creation_info.external_document_refs
        ext_ref_ids = [ref.document_ref_id for ref in ext_refs]
        assert any("zephyr" in ref_id.lower() for ref_id in ext_ref_ids), (
            f"build.spdx: no external ref to zephyr document, got {ext_ref_ids}"
        )

    def test_external_ref_to_app(self, app_doc, build_doc):
        """Test that build.spdx has external reference to app document."""
        if len(app_doc.files) == 0:
            pytest.skip("App document has no files")
        ext_refs = build_doc.creation_info.external_document_refs
        ext_ref_ids = [ref.document_ref_id for ref in ext_refs]
        assert any("app" in ref_id.lower() for ref_id in ext_ref_ids), (
            f"build.spdx: no external ref to app document, got {ext_ref_ids}"
        )

    def test_external_refs_have_checksums(self, build_doc):
        """Test that all external references have checksums."""
        for ref in build_doc.creation_info.external_document_refs:
            assert ref.checksum is not None, (
                f"build.spdx: external ref '{ref.document_ref_id}' has no checksum"
            )

    def test_external_refs_use_sha1(self, build_doc):
        """Test that all external reference checksums use SHA1."""
        for ref in build_doc.creation_info.external_document_refs:
            if ref.checksum:
                assert ref.checksum.algorithm == ChecksumAlgorithm.SHA1, (
                    f"build.spdx: external ref '{ref.document_ref_id}' checksum is not SHA1"
                )

    def test_external_ref_checksums_match_final_documents(
        self, app_doc, zephyr_doc, build_doc, modules_doc, spdx_dir
    ):
        """Test that external ref checksums match the final SPDX files on disk."""
        docs = {
            "app.spdx": app_doc,
            "zephyr.spdx": zephyr_doc,
            "build.spdx": build_doc,
            "modules-deps.spdx": modules_doc,
        }
        paths_by_namespace = {
            doc.creation_info.document_namespace: os.path.join(spdx_dir, filename)
            for filename, doc in docs.items()
        }

        errors = []
        for source_filename, doc in docs.items():
            for ref in doc.creation_info.external_document_refs:
                if ref.checksum is None:
                    continue

                target_path = paths_by_namespace.get(ref.document_uri)
                if target_path is None:
                    errors.append(
                        f"{source_filename}: external ref '{ref.document_ref_id}' points "
                        f"to unknown namespace '{ref.document_uri}'"
                    )
                    continue

                expected_sha1 = file_sha1(target_path)
                if ref.checksum.value != expected_sha1:
                    errors.append(
                        f"{source_filename}: external ref '{ref.document_ref_id}' checksum "
                        f"is '{ref.checksum.value}', expected final file SHA1 '{expected_sha1}'"
                    )

        assert not errors, (
            f"{len(errors)} external document ref checksum mismatch(es):\n" + "\n".join(errors)
        )

    def test_cross_doc_ref_targets_exist(self, app_doc, zephyr_doc, build_doc):
        """Test that cross-document reference targets actually exist in referenced docs.

        Validates that relationships like:
            DocumentRef-app:SPDXRef-File-main.c
            DocumentRef-zephyr:SPDXRef-File-timer.c
        reference SPDX IDs that actually exist in the target documents.
        """
        doc_map = {}

        for doc in [app_doc, zephyr_doc]:
            ref_id = find_doc_ref_id(build_doc, doc.creation_info.document_namespace)
            if ref_id:
                doc_map[ref_id] = doc

        # Collect all cross-document references from relationships
        cross_doc_refs = []
        for rel in build_doc.relationships:
            ref_id = str(rel.related_spdx_element_id)
            if ":" in ref_id and ref_id.startswith("DocumentRef-"):
                cross_doc_refs.append(ref_id)

        assert len(cross_doc_refs) > 0, "build.spdx: no cross-document references found"

        # Validate each cross-document reference
        errors = []
        for ref in cross_doc_refs:
            # Parse DocumentRef-xxx:SPDXRef-yyy format
            doc_ref, spdx_id = ref.split(":", 1)

            if doc_ref not in doc_map:
                errors.append(f"Unknown document ref: {doc_ref}")
                continue

            target_doc = doc_map[doc_ref]

            # Collect all SPDX IDs from the target document
            target_ids = set()
            target_ids.add(target_doc.creation_info.spdx_id)
            for pkg in target_doc.packages:
                target_ids.add(pkg.spdx_id)
            for f in target_doc.files:
                target_ids.add(f.spdx_id)

            if spdx_id not in target_ids:
                errors.append(f"{ref}: target '{spdx_id}' not found in {doc_ref}")

        assert not errors, (
            f"build.spdx: {len(errors)} broken cross-document reference(s):\n"
            + "\n".join(errors[:10])  # Limit output to first 10 errors
        )


class TestBuildTraceability:
    """Tests for source-to-binary traceability in SPDX documents."""

    # --- libapp.a is GENERATED_FROM main.c ---

    def test_libapp_exists_in_build(self, build_doc):
        """Test that libapp.a exists as a file in build.spdx."""
        libapp = find_file_by_name(build_doc, FILE_LIBAPP_A)
        assert libapp is not None, f"build.spdx: {FILE_LIBAPP_A} not found in files"

    def test_libapp_generated_from_main_c(self, build_doc, app_doc):
        """Test that libapp.a has GENERATED_FROM relationship to main.c.

        This verifies the cross-document reference:
        SPDXRef-File-libapp.a GENERATED_FROM DocumentRef-app:SPDXRef-File-main.c
        """
        libapp = find_file_by_name(build_doc, FILE_LIBAPP_A)
        assert libapp is not None, f"build.spdx: {FILE_LIBAPP_A} not found"

        generated_from_rels = get_relationships_for_element(
            build_doc, libapp.spdx_id, RelationshipType.GENERATED_FROM
        )
        assert len(generated_from_rels) > 0, (
            f"build.spdx: {FILE_LIBAPP_A} ({libapp.spdx_id}) has no GENERATED_FROM relationships"
        )

        # Check that at least one relationship points to main.c via cross-doc ref
        main_c_refs = [r for r in generated_from_rels if "main.c" in str(r.related_spdx_element_id)]
        assert len(main_c_refs) == 1, (
            f"build.spdx: expected {FILE_LIBAPP_A} GENERATED_FROM main.c, "
            f"got relationships to: {[r.related_spdx_element_id for r in generated_from_rels]}"
        )

        # hould reference zephyr document for kernel sou uses the app document cross-reference
        app_ref_id = find_doc_ref_id(build_doc, app_doc.creation_info.document_namespace)
        assert app_ref_id is not None, "build.spdx: no external reference to app document"

        app_doc_refs = [r for r in main_c_refs if app_ref_id in str(r.related_spdx_element_id)]
        assert len(app_doc_refs) > 0, (
            f"build.spdx: {FILE_LIBAPP_A} GENERATED_FROM should use {app_ref_id} cross-reference"
        )

    # --- zephyr.elf links libraries ---

    def test_zephyr_elf_exists_in_build(self, build_doc):
        """Test that zephyr.elf exists as a file in build.spdx."""
        zephyr_elf = find_file_by_name(build_doc, FILE_ZEPHYR_ELF)
        assert zephyr_elf is not None, f"build.spdx: {FILE_ZEPHYR_ELF} not found in files"

    @pytest.mark.parametrize(
        "lib_file",
        [FILE_LIBAPP_A, FILE_LIBKERNEL_A, FILE_LIBZEPHYR_A],
        ids=["libapp.a", "libkernel.a", "libzephyr.a"],
    )
    def test_zephyr_elf_static_links(self, build_doc, lib_file):
        """Test that zephyr.elf has STATIC_LINK relationship to expected libraries."""
        zephyr_elf = find_file_by_name(build_doc, FILE_ZEPHYR_ELF)
        assert zephyr_elf is not None, f"build.spdx: {FILE_ZEPHYR_ELF} not found"

        lib = find_file_by_name(build_doc, lib_file)
        assert lib is not None, f"build.spdx: {lib_file} not found"

        static_link_rels = get_relationships_for_element(
            build_doc, zephyr_elf.spdx_id, RelationshipType.STATIC_LINK
        )
        assert len(static_link_rels) > 0, (
            f"build.spdx: {FILE_ZEPHYR_ELF} has no STATIC_LINK relationships"
        )

        lib_links = [r for r in static_link_rels if r.related_spdx_element_id == lib.spdx_id]
        assert len(lib_links) == 1, f"build.spdx: expected {FILE_ZEPHYR_ELF} STATIC_LINK {lib_file}"

    # --- Kernel source traceability ---

    def test_libkernel_generated_from_kernel_sources(self, build_doc, zephyr_doc):
        """Test that libkernel.a is GENERATED_FROM kernel source files."""
        libkernel = find_file_by_name(build_doc, FILE_LIBKERNEL_A)
        assert libkernel is not None, f"build.spdx: {FILE_LIBKERNEL_A} not found"

        generated_from_rels = get_relationships_for_element(
            build_doc, libkernel.spdx_id, RelationshipType.GENERATED_FROM
        )
        assert len(generated_from_rels) > 0, (
            f"build.spdx: {FILE_LIBKERNEL_A} has no GENERATED_FROM relationships"
        )

        # Should reference zephyr document for kernel sources
        zephyr_ref_id = find_doc_ref_id(build_doc, zephyr_doc.creation_info.document_namespace)
        assert zephyr_ref_id is not None, "build.spdx: no external reference to zephyr document"

        zephyr_refs = [
            r for r in generated_from_rels if zephyr_ref_id in str(r.related_spdx_element_id)
        ]
        assert len(zephyr_refs) > 0, (
            f"build.spdx: {FILE_LIBKERNEL_A} should be GENERATED_FROM zephyr sources"
        )

    @pytest.mark.parametrize(
        "expected_source",
        ["timer.c", "sched.c", "thread.c", "sem.c", "mutex.c"],
    )
    def test_libkernel_generated_from_specific_sources(self, build_doc, expected_source):
        """Test that libkernel.a is generated from expected kernel source files."""
        libkernel = find_file_by_name(build_doc, FILE_LIBKERNEL_A)
        assert libkernel is not None, f"build.spdx: {FILE_LIBKERNEL_A} not found"

        generated_from_rels = get_relationships_for_element(
            build_doc, libkernel.spdx_id, RelationshipType.GENERATED_FROM
        )

        source_names = [str(r.related_spdx_element_id) for r in generated_from_rels]
        found = any(expected_source in name for name in source_names)
        assert found, f"build.spdx: {FILE_LIBKERNEL_A} should be GENERATED_FROM {expected_source}"


class TestExtraModules:
    """Tests for the two extra Zephyr modules pulled into the SBOM.

    The build adds two modules via EXTRA_ZEPHYR_MODULES:
      * ``sbom_used_module``   compiled and called from main.c, so its Apache-2.0 source is analyzed
      * ``sbom_unused_module`` declared but builds nothing, so it is present only as an empty source
                               package and a dependency entry.

    Both must surface as source packages in zephyr.spdx and as dependency packages in
    modules-deps.spdx.
    Only the compiled module contributes an analyzed, licensed source file; the declared-only module
    should stay empty.
    """

    @pytest.mark.parametrize(
        "pkg_name",
        [PKG_USED_MODULE_SOURCES, PKG_UNUSED_MODULE_SOURCES],
    )
    def test_module_source_package_exists(self, zephyr_doc, pkg_name):
        """Both module source packages must exist in zephyr.spdx."""
        pkg = find_package_by_name(zephyr_doc, pkg_name)
        pkg_names = [p.name for p in zephyr_doc.packages]
        assert pkg is not None, f"zephyr.spdx: expected '{pkg_name}' package, got {pkg_names}"

    @pytest.mark.parametrize(
        "pkg_name",
        [PKG_USED_MODULE_SOURCES, PKG_UNUSED_MODULE_SOURCES],
    )
    def test_module_source_package_spdx_id(self, zephyr_doc, pkg_name):
        """Module source packages must have a valid, normalized SPDX ID."""
        pkg = find_package_by_name(zephyr_doc, pkg_name)
        assert pkg is not None, f"zephyr.spdx: '{pkg_name}' package not found"
        expected_id = "SPDXRef-" + pkg_name.replace("_", "-")
        assert pkg.spdx_id == expected_id, (
            f"zephyr.spdx: {pkg_name} spdx_id is '{pkg.spdx_id}', expected '{expected_id}'"
        )

    def test_used_module_file_present(self, zephyr_doc):
        """The used module contributes its source file to zephyr.spdx."""
        f = find_file_by_name(zephyr_doc, FILE_USED_MODULE_C)
        assert f is not None, f"zephyr.spdx: {FILE_USED_MODULE_C} not found"

    def test_used_module_file_has_sha1(self, zephyr_doc):
        """The used module's source file must carry a SHA1 checksum."""
        f = find_file_by_name(zephyr_doc, FILE_USED_MODULE_C)
        assert f is not None, f"zephyr.spdx: {FILE_USED_MODULE_C} not found"
        sha1s = [c for c in f.checksums if c.algorithm == ChecksumAlgorithm.SHA1]
        assert len(sha1s) > 0, f"zephyr.spdx: {FILE_USED_MODULE_C} has no SHA1 checksum"

    def test_used_module_license_is_apache(self, zephyr_doc):
        """The used module's file must be analyzed as Apache-2.0."""
        f = find_file_by_name(zephyr_doc, FILE_USED_MODULE_C)
        assert f is not None, f"zephyr.spdx: {FILE_USED_MODULE_C} not found"
        licenses = file_license_ids(f)
        assert any(LICENSE_APACHE in lic for lic in licenses), (
            f"zephyr.spdx: {FILE_USED_MODULE_C} license should be {LICENSE_APACHE}, got {licenses}"
        )

    def test_used_module_files_analyzed(self, zephyr_doc):
        """The used module package must be marked as having analyzed files."""
        pkg = find_package_by_name(zephyr_doc, PKG_USED_MODULE_SOURCES)
        assert pkg is not None, f"zephyr.spdx: '{PKG_USED_MODULE_SOURCES}' package not found"
        assert pkg.files_analyzed, (
            f"zephyr.spdx: {PKG_USED_MODULE_SOURCES} should have files_analyzed=True"
        )

    # --- REUSE.toml supplies license/copyright for a header-less source ---

    def test_reuse_toml_file_present(self, zephyr_doc):
        """The header-less source compiled by the used module is analyzed."""
        f = find_file_by_name(zephyr_doc, FILE_REUSE_TOML_C)
        assert f is not None, f"zephyr.spdx: {FILE_REUSE_TOML_C} not found"

    def test_reuse_toml_license_applied(self, zephyr_doc):
        """A file with no SPDX tag must get its license from REUSE.toml."""
        f = find_file_by_name(zephyr_doc, FILE_REUSE_TOML_C)
        assert f is not None, f"zephyr.spdx: {FILE_REUSE_TOML_C} not found"
        licenses = file_license_ids(f)
        assert any(LICENSE_APACHE in lic for lic in licenses), (
            f"zephyr.spdx: {FILE_REUSE_TOML_C} license should be {LICENSE_APACHE} "
            f"(from REUSE.toml), got {licenses}"
        )

    def test_reuse_toml_copyright_applied(self, zephyr_doc):
        """A file with no SPDX tag must get its copyright from REUSE.toml."""
        f = find_file_by_name(zephyr_doc, FILE_REUSE_TOML_C)
        assert f is not None, f"zephyr.spdx: {FILE_REUSE_TOML_C} not found"
        assert COPYRIGHT_ZEPHYR in str(f.copyright_text), (
            f"zephyr.spdx: {FILE_REUSE_TOML_C} copyright should come from REUSE.toml "
            f"('{COPYRIGHT_ZEPHYR}'), got '{f.copyright_text}'"
        )

    def test_reuse_toml_file_in_used_module_package(self, zephyr_doc):
        """The header-less source must be attributed to the used module package."""
        pkg = find_package_by_name(zephyr_doc, PKG_USED_MODULE_SOURCES)
        assert pkg is not None, f"zephyr.spdx: '{PKG_USED_MODULE_SOURCES}' package not found"
        f = find_file_by_name(zephyr_doc, FILE_REUSE_TOML_C)
        assert f is not None, f"zephyr.spdx: {FILE_REUSE_TOML_C} not found"
        contained = {
            str(r.related_spdx_element_id)
            for r in get_relationships_for_element(
                zephyr_doc, pkg.spdx_id, RelationshipType.CONTAINS
            )
        }
        assert f.spdx_id in contained, (
            f"zephyr.spdx: {PKG_USED_MODULE_SOURCES} does not CONTAIN {FILE_REUSE_TOML_C}"
        )

    def test_unused_module_has_no_files(self, zephyr_doc):
        """The unused module is declared but compiles nothing, its source package must therefore
        exist yet stay empty.
        """
        pkg = find_package_by_name(zephyr_doc, PKG_UNUSED_MODULE_SOURCES)
        assert pkg is not None, f"zephyr.spdx: '{PKG_UNUSED_MODULE_SOURCES}' package not found"
        assert not pkg.files_analyzed, (
            f"zephyr.spdx: {PKG_UNUSED_MODULE_SOURCES} should have files_analyzed=False"
        )
        contains = get_relationships_for_element(zephyr_doc, pkg.spdx_id, RelationshipType.CONTAINS)
        assert len(contains) == 0, (
            f"zephyr.spdx: {PKG_UNUSED_MODULE_SOURCES} should contain no files, got {len(contains)}"
        )

    def test_unused_module_source_absent_from_sbom(
        self, app_doc, zephyr_doc, build_doc, modules_doc
    ):
        """A module's source file that is never compiled must not leak into the SBOM."""
        docs = {
            "app.spdx": app_doc,
            "zephyr.spdx": zephyr_doc,
            "build.spdx": build_doc,
            "modules-deps.spdx": modules_doc,
        }
        for doc_name, doc in docs.items():
            offenders = [
                f.name for f in doc.files if os.path.basename(f.name) == FILE_UNUSED_MODULE_C
            ]
            assert not offenders, (
                f"{doc_name}: lists un-compiled source(s) that should be absent: {offenders}"
            )

    def test_used_module_copyright(self, zephyr_doc):
        """The used module file must expose exactly its copyright text."""
        f = find_file_by_name(zephyr_doc, FILE_USED_MODULE_C)
        assert f is not None, f"zephyr.spdx: {FILE_USED_MODULE_C} not found"
        assert str(f.copyright_text) == EXPECTED_USED_MODULE_COPYRIGHT, (
            f"zephyr.spdx: {FILE_USED_MODULE_C} copyright is '{f.copyright_text}', "
            f"expected '{EXPECTED_USED_MODULE_COPYRIGHT}'"
        )

    def test_used_module_package_contains_its_file(self, zephyr_doc):
        """The used module package must CONTAIN its source file."""
        pkg = find_package_by_name(zephyr_doc, PKG_USED_MODULE_SOURCES)
        assert pkg is not None, f"zephyr.spdx: '{PKG_USED_MODULE_SOURCES}' package not found"
        f = find_file_by_name(zephyr_doc, FILE_USED_MODULE_C)
        assert f is not None, f"zephyr.spdx: {FILE_USED_MODULE_C} not found"

        contained = {
            str(r.related_spdx_element_id)
            for r in get_relationships_for_element(
                zephyr_doc, pkg.spdx_id, RelationshipType.CONTAINS
            )
        }
        assert f.spdx_id in contained, (
            f"zephyr.spdx: {PKG_USED_MODULE_SOURCES} does not CONTAIN {FILE_USED_MODULE_C}"
        )

    @pytest.mark.parametrize(
        "pkg_name",
        [PKG_USED_MODULE_DEPS, PKG_UNUSED_MODULE_DEPS],
    )
    def test_module_deps_package_exists(self, modules_doc, pkg_name):
        """Both modules must be listed as dependency packages in modules-deps.spdx."""
        pkg = find_package_by_name(modules_doc, pkg_name)
        pkg_names = [p.name for p in modules_doc.packages]
        assert pkg is not None, f"modules-deps.spdx: expected '{pkg_name}' package, got {pkg_names}"

    @pytest.mark.parametrize(
        "pkg_name",
        [PKG_USED_MODULE_DEPS, PKG_UNUSED_MODULE_DEPS],
    )
    def test_module_deps_depend_on_zephyr(self, modules_doc, pkg_name):
        """Each module dependency must be a DEPENDENCY_OF the zephyr dependency."""
        pkg = find_package_by_name(modules_doc, pkg_name)
        assert pkg is not None, f"modules-deps.spdx: '{pkg_name}' package not found"
        dep_rels = get_relationships_for_element(
            modules_doc, pkg.spdx_id, RelationshipType.DEPENDENCY_OF
        )
        assert len(dep_rels) > 0, f"modules-deps.spdx: {pkg_name} has no DEPENDENCY_OF relationship"
