/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_RV32M1_CNTR_H_
#define ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_RV32M1_CNTR_H_



#endif /* ZEPHYR_BT_CONTROLLER_LL_SW_OPENISA_HAL_RV32M1_CNTR_H_ */
