CONFIG_PRINTK=y
CONFIG_MBOX=y



# CPU Frequency Subsystem Configuration
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_LOG_LEVEL_DBG=y
CONFIG_CPU_FREQ_INTERVAL_MS=5000
CONFIG_CPU_FREQ_POLICY_PRESSURE=y
CONFIG_CPU_FREQ_POLICY_PRESSURE_LOWEST_PRIO=10
CONFIG_LOG=y